name: Module-Refresh
version: 0.01
author: Jesse Vincent <jesse@bestpractical.com>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
